# Generated by Django 4.1.3 on 2022-12-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0007_remove_event_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="accountLogin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="accountSignUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=255)),
                ("lastName", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("rePassword", models.CharField(max_length=255)),
            ],
        ),
    ]
