# Generated by Django 4.1.3 on 2022-12-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0008_accountlogin_accountsignup"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountlogin",
            name="firstName",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="accountlogin",
            name="password",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
